---
virtual_machines:
  - name: openshift-master
    node_type: master
    system_ram_mb: 24576
    system_cpus: 4
  - name: openshift-node-1
    node_type: nodes
    system_ram_mb: 24576
    system_cpus: 4
  - name: openshift-node-2
    node_type: nodes
    system_ram_mb: 24576
    system_cpus: 4
host_type: fedora
centos_genericcloud_url: https://download.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.qcow2
image_destination_name: Fedora-x86_64-GenericCloud.qcow2
images_directory: /home/images
bridge_name: br0
bridge_networking: true
bridge_physical_nic: enp1s0f1
bridge_network_name: br0
bridge_network_cidr: 192.168.1.0/24
spare_disk_size_megs: 20480
spare_disk_location: /var/lib/libvirt/images
increase_root_size_gigs: 35
