---
sudo: required
language: python
python: '2.7'

services:
    - docker

before_install:
    # perform updates
    - sudo apt-get update -qq

    # install ansible
    - sudo apt-get install -qq python-apt

install:
    - pip install ansible
    - pip install ansible-lint
    - ansible-galaxy install -r requirements.yml

script:
    - ansible-lint virt-host-setup.yml
    - ansible-lint bootstrap.yml
    - ansible-lint vm-teardown.yml
