---
- name: Install epel
  package:
    name: epel-release
    state: present

- name: Install deps for openshift-ansible
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ansible
    - pyOpenSSL
    - python-cryptography
    - python-lxml

- name: Clone openshift-ansible
  git:
    repo: https://github.com/openshift/openshift-ansible.git
    version: master
    dest: /root/openshift-ansible
