---
- name: Install epel
  package:
    name: epel-release
    state: present

- name: Install deps for openshift-ansible
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - ansible
      - pyOpenSSL
      - python-cryptography
      - python-lxml
  when: not (ocp4_install | default('False') | bool)

- name: Set openshift_ansible_version to devel-40 for ocp4
  set_fact:
    openshift_ansible_version: "devel-40"
  when: ocp4_install | default('False') | bool

- name: Clone openshift-ansible
  git:
    repo: "{{ openshift_ansible_repo }}"
    version: "{{ openshift_ansible_version }}"
    dest: /root/openshift-ansible
    force: yes
