# vim: set tabstop=2 shiftwidth=2 ft=yaml :
---
centos_genericcloud_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
image_destination_name: CentOS-7-x86_64-GenericCloud.qcow2
host_type: "centos"
images_directory: /home/images/3node
spare_disk_location: /home/images/3node
ssh_proxy_user: root
ssh_proxy_host: virthost
vm_ssh_key_path: /home/lmadsen/.ssh/3node

# network configuration for bridged network on virtual machine
bridge_networking: true
bridge_name: br1
bridge_physical_nic: "enp3s0"
bridge_network_name: "br1"
bridge_network_cidr: 192.168.3.0/24
domain_name: openshift.nfvpe.site

# network configuration for spinup.sh in redhat-nfvpe.vm-spinup role
system_network: 192.168.3.0
system_netmask: 255.255.255.0
system_broadcast: 192.168.3.255
system_gateway: 192.168.3.1
system_nameservers: 192.168.3.1
system_dns_search: openshift.nfvpe.site

# list of virtual machines to create
virtual_machines:
  - name: apb-tools
    node_type: other
    system_ram_mb: 4096
    static_ip: 192.168.3.79
