---

- name: Create images for spare disks
  shell: >
    qemu-img create -f raw {{ spare_disk_location }}/{{ item }}.img {{ spare_disk_size_megs }}M
  args:
    creates: "{{ spare_disk_location }}/{{ item }}.img"
  with_items: "{{ virtual_machines }}"

- name: Attach disk
  shell: >
    virsh attach-disk "{{ item }}" {{ spare_disk_location }}/{{ item }}.img {{ vm_disk_device }} --cache none &&
    touch {{ spare_disk_location }}/.attached-{{ item }}
  args:
    creates: "{{ spare_disk_location }}/.attached-{{ item }}"
  with_items: "{{ virtual_machines }}"
