---

- name: Create images for spare disks
  shell: >
    dd if=/dev/zero of={{ spare_disk_location }}/{{ item }}.img bs=1M count={{ spare_disk_size_megs }}
  args:
    creates: "{{ spare_disk_location }}/{{ item }}.img"
  with_items: "{{ virtual_machines }}"

- name: Attach disk
  shell: >
    virsh attach-disk "{{ item }}" {{ spare_disk_location }}/{{ item }}.img {{ vm_disk_device }} --cache none &&
    touch {{ spare_disk_location }}/.attached-{{ item }}
  args:
    creates: "{{ spare_disk_location }}/.attached-{{ item }}"
  with_items: "{{ virtual_machines }}"
