---
- hosts: virthosts
  tasks: []
  pre_tasks:
    - name: Install python36 on virt host
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - python36
     # when:
  roles:
    - { role: redhat-nfvpe.vm-spinup }
    - { role: openshift-ansible-deps }
